#ifndef EXEPTION_HPP
#define EXEPTION_HPP

enum Exception
{
    AAAA_TEST_FAILED,
    BBBB_TEST_FAILED,
    CCCC_TEST_FAILED,
    DDDD_TEST_FAILED,
    ACAC_TEST_FAILED,
    ABCD_TEST_FAILED,
    INCORRECT_AMOUNT_OF_ARGUMENTS,
    CHAR_NOT_INT
};

#endif