#ifndef EXEPTION_HPP
#define EXEPTION_HPP

enum Exception
{
    TEST_AAAA_FAILED,
    TEST_BBBB_FAILED,
    TEST_CCCC_FAILED,
    TEST_DDDD_FAILED,
    TEST_ACAC_FAILED,
    TEST_ABCD_FAILED,
    TEST_111_2_3_FAILED,
    TEST_222_0_1_FAILED,
    TEST_11_99_4_FAILED,
    TEST_3_4_2_FAILED,
    INCORRECT_AMOUNT_OF_ARGUMENTS,
    CHAR_NOT_INT
};

#endif